<?php
 
/**
 * Implementation of hook_menu().
 */

function opendata_menu() {  

  $items = array();
  
  $items['admin/content/opendata'] = array(
    'title' => 'OpenData', 
    'description' => t('General Information'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opendata_general'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'opendata.general.inc',
  );
  /*
  $items['admin/content/od'] = array(
    'title' => 'OpenData',
    'description' => t('General Information'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opendata_general'),
    'access callback' => TRUE,
    'file' => 'opendata.main.inc',
  );
  */
  return $items;
}
